"""Bundled evolution-stage weight snapshots: meta eval quality must not regress.

The four ``quantum_oval_stage{1..4}`` snapshots power evolution mode's
"training stages" cars.  They are eval-selected when regenerated by
``tools/make_stages.py``; this test pins the invariant that later stages are
never worse than earlier ones, so a bad regeneration cannot land silently.
"""

from __future__ import annotations

import json
from pathlib import Path

WEIGHTS_DIR = Path(__file__).resolve().parent.parent / "traqmania" / "weights"
EVAL_KEYS = ("eval_episodes", "eval_laps", "eval_best_lap")


def _stage_meta(i: int) -> dict:
    npz = WEIGHTS_DIR / f"quantum_oval_stage{i}.npz"
    meta_path = WEIGHTS_DIR / f"quantum_oval_stage{i}.meta.json"
    assert npz.is_file(), f"missing weights file {npz.name}"
    assert meta_path.is_file(), f"missing meta file {meta_path.name}"
    return json.loads(meta_path.read_text(encoding="utf-8"))


def _quality(meta: dict) -> tuple:
    """Eval quality ordering: more clean laps first, then faster best lap."""
    lap = meta["eval_best_lap"]
    return (meta["eval_laps"], -lap if lap is not None else -float("inf"))


def test_oval_stage_meta_eval_fields_present():
    for i in range(1, 5):
        meta = _stage_meta(i)
        assert meta["agent"] == "quantum" and meta["track"] == "oval"
        assert meta["stage"] == i
        for key in EVAL_KEYS:
            assert key in meta, f"stage{i} meta missing '{key}'"
        assert meta["eval_episodes"] >= 1
        assert meta["eval_laps"] >= 0
        lap = meta["eval_best_lap"]
        assert lap is None or lap > 0


def test_oval_stage_meta_quality_monotonic_nondecreasing():
    metas = [_stage_meta(i) for i in range(1, 5)]
    episodes = [m["episodes"] for m in metas]
    assert episodes == sorted(episodes), f"stage episodes not increasing: {episodes}"
    assert len(set(episodes)) == 4, f"stage episodes not distinct: {episodes}"
    qualities = [_quality(m) for m in metas]
    assert qualities == sorted(qualities), (
        f"stage eval quality regresses across stages 1..4: {qualities}")
